### ISSUE TITLE
1.5.0버젼 오류

### ISSUE THREAD

**Issue by JacksonPk** [tksrl0379/LocalCurrency#2]
1. 지역 다운로드 미완료 시에도 버튼 클릭이 비활성화 되어지는 상황.

2. km 거리 UI 가 다 보여지지 않는 상황.

3. 검색창이 너무 위에 가있고/ 그림자 구현 필요.

4. 처음 다운로드시 설정에서 도시 선택이 아무것도 없으면 검색창 누를시 앱 강제종료됌.

**Comment by tksrl0379** [comment]
1번은 이후 수정
